import { create } from "zustand";

export const useTodoModalStore = create((set) => ({
  // cards: [
  //   {
  //     id: 0,
  //     title: "",
  //     description: "",
  //     tags: [""],
  //     dueDate: "",
  //     assignee: {
  //       porfileImageUrl: "",
  //       nickname: "",
  //       id: 0,
  //     },
  //     imageUrl: "",
  //     teamId: "",
  //     columnId: 0,
  //     createdAt: "",
  //     updatedAt: "",
  //   },
  // ],
  // setCards: (state) => set({ cards: state }),
  //  column: {
  //   result: "",
  //   data: {
  //     id: 0,
  //     title: "",
  //     teamId: "",
  //     createdAt: "",
  //     updatedAt: "",
  //   },
  // },
  // setColumns: (state) => set({ column: state }),
  // columnArray: [
  //   {
  //     result: "",
  //     data: {
  //       id: 0,
  //       title: "",
  //       teamId: "",
  //       createdAt: "",
  //       updatedAt: "",
  //     },
  //   },
  // ],
  // setColumnArray: (state) => set({ columns: state }),
  // cardArray: [
  //   {
  //     id: 0,
  //     title: "",
  //     description: "",
  //     tags: [""],
  //     dueDate: "",
  //     assignee: {
  //       porfileImageUrl: "",
  //       nickname: "",
  //       id: 0,
  //     },
  //     imageUrl: "",
  //     teamId: "",
  //     columnId: 0,
  //     createdAt: "",
  //     updatedAt: "",
  //   },
  // ],
  // setCardArray: (state) => set({ cardArray: state }),
  editedCardId: 0,
  setEditedCardId: (state) => set({ editedCardId: state }),
  isCreateCardOpen: false,
  setIsCreateCardOpen: (state) => set({ isCreateCardOpen: state }),
  isEditCardOpen: false,
  setIsEditCardOpen: (state) => set({ isEditCardOpen: state }),
  isCreateColumnOpen: false,
  setIsCreateColumnOpen: (state) => set({ isCreateColumnOpen: state }),
  isEditColumnOpen: false,
  setIsEditColumnOpen: (state) => set({ isEditColumnOpen: state }),
  isShowCardOpen: false,
  setIsShowCardOpen: (state) => set({ isShowCardOpen: state }),
}));
